### ISSUE TITLE
bracket lookup prefers system fonts to actual path

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#24]
If I have a font both in my system folder and in the local directory even when the absolute path is given, luaotfload uses the system font:

```
\input luaotfload.sty
\directlua{texio.write_nl(kpse.find_file("BabelStoneTibetan.ttf"))}

\font\test=[G:/Z-Test/BabelStoneTibetan.ttf] at 10 pt
\test A
\bye
```

```
./BabelStoneTibetan.ttf [1{d:/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdf
tex.map}])<c:/Windows/Fonts/BabelStoneTibetan.ttf><d:/texlive/2018/texmf-dist/fo
nts/type1/public/amsfonts/cm/cmr10.pfb>

```

Deleting the luc/lua in the font cache solve the problem:

~~~
./BabelStoneTibetan.ttf [1{d:/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdf
tex.map}])<g:/Z-Test/BabelStoneTibetan.ttf><d:/texlive/2018/texmf-dist/fonts/typ
e1/public/amsfonts/cm/cmr10.pfb>
~~~

But this should imho not be necessary.  See also issue #23 .

**Comment by khaledhosny** [comment]
I guess this is because the font cache uses “sanitized” base file name as a key. This mean any two font files that happen to have the same named after dropping the directory part and “sanitizing” the file name are considered the same. This is a rather fragile design, I’d expect some unique property like checksum to be used as a key, or the full file path verbatim without any changes.

**Comment by zauguin** [comment]
@u-fischer The lookup always prefers the path, but if the fontloader determines that it is the same font as the cached one, the cached one is reused. The same font not only means the same name, it also compares the size and the time of the last change to the font file, so at least on Linux is had a hard time even reproducing this for the same file because I always had different change times, so I wold not expect this to occur randomly.

Do you know about any situation where this triggers for *different* files?

Anyway, iff we consider this to be a problem, the fontloader is responsible. But I would prefer to keep the current behavior because it is allows reusing the cache for linked files.

**Comment by u-fischer** [comment]
@zauguin I think that if the fontloader tests the fonts for equality we can live with this behaviour. I guess that as it is in the fontloader, we can't issue a message about the replacement in the log, so I will only document it.
